version: '3.3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    depends_on: [mongo]

  node:
    image: node:14
    volumes:
      - "./:/app"
    ports:
      - "3000:3000"
    working_dir: /app
    command: "npm run dev"
    depends_on: [mongo, mongo-express]